# Generated by Django 3.2.6 on 2021-08-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='use_other_template',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
