# Generated by Django 3.2.6 on 2021-08-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpage_use_other_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='use_other_template',
        ),
    ]
