# Generated by Django 3.2.6 on 2021-08-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogpage_use_other_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='phone',
            field=models.IntegerField(default=99899000112),
        ),
    ]
